server:
  port: 8888

api:
  config: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-services
          uri: http://localhost:8080
          predicates:
            - Path=${api.config}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-services
          uri: http://localhost:8081
          predicates:
            - Path=${api.config}/profile/users/**
          filters:
            - StripPrefix=2